name: BluBlock
description: "Ein Tool zur automatischen Contentmoderation."
publish_to: 'none'
version: 0.3.1+12

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.3+1
  webview_flutter: ^4.8.0
  logging: ^1.0.2
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.0.0
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.3.0

dependency_overrides:
  webview_flutter_android: 3.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  

flutter:
  uses-material-design: true

flutter_icons:
  android: true  
  ios: true  
  image_path: "assets/BluBlock.png"
  adaptive_icon_background: "assets/BluBlock.png"  
  adaptive_icon_foreground: "assets/BluBlock.png" 
