name: BluBlock
description: "Ein Tool zur automatischen Contentmoderation."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.3+1
  webview_flutter: ^3.0.4
  logging: ^1.0.2
  http: ^0.13.3
  intl: ^0.17.0
  provider: ^6.0.0
  workmanager: ^0.5.2
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.9.2"  

flutter:
  uses-material-design: true

flutter_icons:
  android: true  
  ios: true  
  image_path: "assets/BluBlock.png"
  adaptive_icon_background: "assets/BluBlock.png"  
  adaptive_icon_foreground: "assets/BluBlock.png" 
